// <auto-generated />
namespace PS.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Request_Droped : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Request_Droped));
        
        string IMigrationMetadata.Id
        {
            get { return "201805071043529_Request_Droped"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
